service: s3-bucket-crud-api
provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    # accepted binary type for file uploads
    binaryMediaTypes:
      - 'multipart/form-data'
functions:
  # sync upload
  uploadFile:
    handler: build.uploadFile
    events:
      - http:
          method: post
          path: upload
          cors: true
resources:
  Resources:
    MyServerlessBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-example1-bucket
    # define a policy for an existing role
    UploadFilePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: UploadObjects
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: LambdaPutObjects
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectTagging
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: MyServerlessBucket
                    - "/*"
        Roles:
          - serverless-s3-dev